version: '3.5'

services:
  app:
    container_name: ENVIRONMENT-NAME-PROJECT-NAME
    image: IMAGE-NAME:IMAGE-TAG
    volumes:
      - MOUNT-DATA-FOLDER/PROJECT-NAME:/usr/src/app/storage
    environment:
      - NODE_ENV=NODE_ENV_VALUE
    ports:
      - P-MAPPING:3000
    env_file:
      - .env
    restart: unless-stopped
    pull_policy: always

